# Generated by Django 5.0.9 on 2024-11-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('cat_id', models.AutoField(db_column='Cat_ID', primary_key=True, serialize=False)),
                ('cat_name', models.CharField(db_column='Cat_Name', max_length=100)),
            ],
            options={
                'db_table': 'Categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('itm_id', models.AutoField(db_column='Itm_ID', primary_key=True, serialize=False)),
                ('itm_name', models.CharField(db_column='Itm_Name', max_length=100)),
                ('itm_ean', models.CharField(blank=True, db_column='Itm_EAN', max_length=13, null=True, unique=True)),
                ('itm_price', models.DecimalField(blank=True, db_column='Itm_Price', decimal_places=2, max_digits=10, null=True)),
                ('itm_minqty', models.IntegerField(blank=True, db_column='Itm_MinQty', null=True)),
                ('itm_isactive', models.BooleanField(blank=True, db_column='Itm_IsActive', null=True)),
                ('itm_updatedate', models.DateTimeField(blank=True, db_column='Itm_UpdateDate', null=True)),
            ],
            options={
                'db_table': 'Items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stk_id', models.AutoField(db_column='Stk_ID', primary_key=True, serialize=False)),
                ('stk_qty', models.IntegerField(db_column='Stk_Qty')),
                ('stk_updatedate', models.DateTimeField(blank=True, db_column='Stk_UpdateDate', null=True)),
            ],
            options={
                'db_table': 'Stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('sup_id', models.AutoField(db_column='Sup_ID', primary_key=True, serialize=False)),
                ('sup_name', models.CharField(db_column='Sup_Name', max_length=100)),
                ('sup_taxid', models.CharField(db_column='Sup_TaxID', max_length=15, unique=True)),
                ('sup_email', models.CharField(blank=True, db_column='Sup_Email', max_length=100, null=True)),
                ('sup_phone', models.CharField(blank=True, db_column='Sup_Phone', max_length=20, null=True)),
                ('sup_paymentterms', models.CharField(blank=True, db_column='Sup_PaymentTerms', max_length=50, null=True)),
                ('sup_address', models.CharField(blank=True, db_column='Sup_Address', max_length=200, null=True)),
                ('sup_isactive', models.BooleanField(blank=True, db_column='Sup_IsActive', null=True)),
                ('sup_updatedate', models.DateTimeField(blank=True, db_column='Sup_UpdateDate', null=True)),
            ],
            options={
                'db_table': 'Suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('uni_id', models.AutoField(db_column='Unit_ID', primary_key=True, serialize=False)),
                ('uni_code', models.CharField(db_column='Unit_Code', max_length=10)),
            ],
            options={
                'db_table': 'Units',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('wh_id', models.AutoField(db_column='Wh_ID', primary_key=True, serialize=False)),
                ('wh_name', models.CharField(db_column='Wh_Name', max_length=100)),
                ('wh_code', models.CharField(blank=True, db_column='Wh_Code', max_length=10, null=True, unique=True)),
                ('wh_location', models.CharField(blank=True, db_column='Wh_Location', max_length=100, null=True)),
                ('whs_isactive', models.BooleanField(blank=True, db_column='Whs_IsActive', null=True)),
                ('whs_updatedate', models.DateTimeField(blank=True, db_column='Whs_UpdateDate', null=True)),
            ],
            options={
                'db_table': 'Warehouses',
                'managed': False,
            },
        ),
    ]
